# -*- coding: utf-8 -*-
"""Helloworld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10yp31ngfZx_8adCh7xPYP38mpQzxwio8
"""

print("Hello World!")